// Post-build: generate out/_headers for Cloudflare with strong security headers
// and a strict CSP. Static export has no per-request nonce, so we hash every
// inline <script> (Next's bootstrap + our JSON-LD) and pin the hashes in
// script-src — no 'unsafe-inline' for scripts. Run after `next build`.
//
//   node tools/gen-headers.mjs

import { createHash } from "node:crypto";
import { readdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const OUT = join(fileURLToPath(new URL(".", import.meta.url)), "..", "out");

async function htmlFiles(dir) {
  const out = [];
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const p = join(dir, entry.name);
    if (entry.isDirectory()) out.push(...(await htmlFiles(p)));
    else if (entry.name.endsWith(".html")) out.push(p);
  }
  return out;
}

// Extract the text content of every inline <script> (no src attribute).
const INLINE_SCRIPT = /<script(?![^>]*\ssrc=)[^>]*>([\s\S]*?)<\/script>/gi;

async function main() {
  const files = await htmlFiles(OUT);
  const hashes = new Set();
  for (const file of files) {
    const html = await readFile(file, "utf8");
    let m;
    while ((m = INLINE_SCRIPT.exec(html)) !== null) {
      const body = m[1];
      if (body === undefined || body.length === 0) continue;
      const digest = createHash("sha256").update(body, "utf8").digest("base64");
      hashes.add(`'sha256-${digest}'`);
    }
  }

  const scriptSrc = ["'self'", ...[...hashes].sort()].join(" ");
  const csp = [
    "default-src 'self'",
    "base-uri 'none'",
    "object-src 'none'",
    "frame-ancestors 'none'",
    "form-action 'self'",
    "img-src 'self' data:",
    "font-src 'self'",
    // inline style attributes (style={{…}} in components) require this; style
    // injection is a far weaker vector than script injection, which stays locked.
    "style-src 'self' 'unsafe-inline'",
    `script-src ${scriptSrc}`,
    "connect-src 'self'",
    "manifest-src 'self'",
    "upgrade-insecure-requests",
  ].join("; ");

  const headers = `# Generated by tools/gen-headers.mjs — do not edit by hand.
/*
  Content-Security-Policy: ${csp}
  Strict-Transport-Security: max-age=63072000; includeSubDomains; preload
  X-Content-Type-Options: nosniff
  Referrer-Policy: strict-origin-when-cross-origin
  X-Frame-Options: DENY
  Cross-Origin-Opener-Policy: same-origin
  Cross-Origin-Resource-Policy: same-origin
  Permissions-Policy: camera=(), microphone=(), geolocation=(), interest-cohort=()
  X-DNS-Prefetch-Control: off

# Long-cache the immutable Next build assets.
/_next/static/*
  Cache-Control: public, max-age=31536000, immutable
`;

  await writeFile(join(OUT, "_headers"), headers, "utf8");
  console.log(`wrote out/_headers · ${hashes.size} inline-script hashes pinned in script-src`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
