// Post-build: hash every inline <script> in the static export and generate
// worker/csp.mjs — the strict CSP + security headers served by worker/index.mjs.
// (A _headers file can't carry this CSP: Cloudflare caps _headers lines at
// 2000 chars and the per-build hash list is longer.) Run after `next build`.
//
//   node tools/gen-headers.mjs

import { createHash } from "node:crypto";
import { readdir, readFile, writeFile, rm } from "node:fs/promises";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(fileURLToPath(new URL(".", import.meta.url)), "..");
const OUT = join(ROOT, "out");

async function htmlFiles(dir) {
  const found = [];
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const p = join(dir, entry.name);
    if (entry.isDirectory()) found.push(...(await htmlFiles(p)));
    else if (entry.name.endsWith(".html")) found.push(p);
  }
  return found;
}

// Inline <script> only (no src attribute).
const INLINE_SCRIPT = /<script(?![^>]*\ssrc=)[^>]*>([\s\S]*?)<\/script>/gi;

async function main() {
  const files = await htmlFiles(OUT);
  const hashes = new Set();
  for (const file of files) {
    const html = await readFile(file, "utf8");
    let m;
    while ((m = INLINE_SCRIPT.exec(html)) !== null) {
      const body = m[1];
      if (body === undefined || body.length === 0) continue;
      const digest = createHash("sha256").update(body, "utf8").digest("base64");
      hashes.add(`'sha256-${digest}'`);
    }
  }

  const scriptSrc = ["'self'", ...[...hashes].sort()].join(" ");
  const csp = [
    "default-src 'self'",
    "base-uri 'none'",
    "object-src 'none'",
    "frame-ancestors 'none'",
    "form-action 'self'",
    "img-src 'self' data:",
    "font-src 'self'",
    // inline style attributes (style={{…}}) need this; script-src stays locked.
    "style-src 'self' 'unsafe-inline'",
    `script-src ${scriptSrc}`,
    "connect-src 'self'",
    "manifest-src 'self'",
    "upgrade-insecure-requests",
  ].join("; ");

  const module = `// Generated by tools/gen-headers.mjs — do not edit by hand.
export const CSP =
  ${JSON.stringify(csp)};

export const SECURITY_HEADERS = {
  "Strict-Transport-Security": "max-age=63072000; includeSubDomains; preload",
  "X-Content-Type-Options": "nosniff",
  "Referrer-Policy": "strict-origin-when-cross-origin",
  "X-Frame-Options": "DENY",
  "Cross-Origin-Opener-Policy": "same-origin",
  "Cross-Origin-Resource-Policy": "same-origin",
  "Permissions-Policy": "camera=(), microphone=(), geolocation=(), interest-cohort=()",
  "X-DNS-Prefetch-Control": "off",
};
`;

  await writeFile(join(ROOT, "worker", "csp.mjs"), module, "utf8");
  // A stale _headers from an older build would fail Cloudflare's 2000-char
  // line limit at upload — make sure it's gone.
  await rm(join(OUT, "_headers"), { force: true });
  console.log(`wrote worker/csp.mjs · ${hashes.size} inline-script hashes pinned in script-src`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
